#include <cstdint>

extern "C" void __cdecl _free(void* _Memory);

extern "C" void __cdecl ___free_lc_time(std::uint32_t* param_1)
{
    if (param_1 != nullptr)
    {
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[1])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[2])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[3])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[4])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[5])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[6])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[8])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[9])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[10])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x0b])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x0c])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x0d])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[7])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x0e])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x0f])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x10])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x11])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x12])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x13])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x14])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x15])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x16])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x17])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x18])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x19])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1a])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1b])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1c])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1d])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1e])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x1f])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x20])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x21])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x22])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x23])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x24])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x25])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x26])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x27])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x28])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x29])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x2a])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x2f])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x30])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x31])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x32])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x33])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x34])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x2e])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x36])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x37])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x38])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x39])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3a])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3b])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x35])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3c])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3d])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3e])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x3f])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x40])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x41])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x42])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x43])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x44])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x45])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x46])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x47])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x48])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x49])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4a])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4b])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4c])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4d])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4e])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x4f])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x50])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x51])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x52])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x53])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x54])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x55])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x56])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x57])));
        _free(reinterpret_cast<void*>(static_cast<std::uintptr_t>(param_1[0x58])));
    }
}